nager/Nager.Date

- Nager.Date/PublicHolidays/LithuaniaProvider.cs
Lithuania also has Easter Monday.
https://en.wikipedia.org/wiki/Public_holidays_in_Lithuania
> The first Sunday after the full moon that occurs on or soonest after 21 March **and following Monday**
> Add Easter monday to Lithuania

- Nager.Date.UnitTest/Nager.Date.UnitTest.csproj
- Nager.Date.UnitTest/UnitTestGermany.cs
- Nager.Date/DateSystem.cs
- Nager.Date/Model/PublicHoliday.cs
Hi Tino,
the problem was not with the county-specific public holiday (Epiphany-Day) but if you check a global public holiday with the method `IsOfficialPublicHolidayByCounty` (like Christmas-Day).
In that case the Counties `string[]` is null and the `Any()` LINQ expression will fail with an`ArgumentNullException`
I've updated bot methods `IsOfficialPublicHolidayByCounty` and `IsAdministrationPublicHolidayByCounty` to respect that Counties might be null in case of global public holiday.
Cheers,
Marcus
> Fix for issue #22

- Nager.Date.UnitTest/UnitTestUnitedKingdom.cs
- Nager.Date/PublicHolidays/UnitedKingdomProvider.cs
St Patricks Day was incorrectly set as coincident with Battle of Boyne (cut paste error I think) corrected to 17 March as per https://en.wikipedia.org/wiki/Saint_Patrick%27s_Day
> Fix St Patricks Day

- Src/Nager.Date/PublicHolidays/GermanyProvider.cs
December 24th is/would be what's called 'Weihnachten' in Germany, Dec 25th however is 'Erster Weihnachts(feier)tag' and Dec 26th is 'Zweiter Weihnachts(feier)tag'. I opted for the somewhat more commonly used 'Weihnachtstag'.
See also
- https://de.wikipedia.org/wiki/Gesetzliche_Feiertage_in_Deutschland
- https://www.innenministerium.bayern.de/suk/bayern/feiertage/
- https://innen.hessen.de/buerger-staat/gesetzliche-feiertage
- etc..
> Fixed LocalNames for German Christmas Holidays

- Src/Nager.Date.UnitTest/Country/HungaryTest.cs
- Src/Nager.Date.UnitTest/Nager.Date.UnitTest.csproj
- Src/Nager.Date/PublicHolidays/HungaryProvider.cs
This pull request contains:
1. Good friday as a holiday as it is declared as a holiday since 2017.
Reference link: [Public holidays in hungary](https://en.wikipedia.org/wiki/Public_holidays_in_Hungary)
2. Updated country code of Hungary from **EE** to **HU**.
Reference link: [Hungary country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#HU)
3. Added unit tests for Hungary public holidays(For year 2018). Tests for all public holidays are passing successfully.
> #72 Good Friday in hungary

- Src/Nager.Date.UnitTest/Country/KosovoTest.cs
- Src/Nager.Date.UnitTest/Nager.Date.UnitTest.csproj
- Src/Nager.Date/CountryCode.cs
- Src/Nager.Date/DateSystem.cs
- Src/Nager.Date/PublicHolidays/KosovoProvider.cs
This PR contains,
- Added new country called Kosovo.
- Included Orthodox as well as catholic holidays
- Added Country code for Kosovo
- Added Kosovo in _publicHolidayProviders dictionary, also added missing country AlbaniaProvider to same dictionary.
> Added Kosovo country

- Src/Nager.Date/PublicHolidays/BulgariaProvider.cs
The months for "Unification Day" and "Independence Day" were incorrect. Nothing else was changed.
> Changed dates to properly reflect PublicHolidays for Bulgaria

- Src/Nager.Date/PublicHolidays/UnitedKingdomProvider.cs
Implements #149.
Added conditional one-off change to Early May Bank Holiday. Please let me know if this doesn't fit in with your standards and I'll modify accordingly.
It's a one off change just for 2020.
> Added UK May Bank Holiday Change VE Day 2020 - #149

- Src/Nager.Date/PublicHolidays/NetherlandsProvider.cs
> The Dutch have a two-day holiday, called Eerste Paasdag on Sunday and Tweede Paasdag on Monday (lit. First Easter Day and Second Easter Day)
https://en.wikipedia.org/wiki/Public_holidays_in_the_Netherlands
I also changed the spelling of the 2 Christmas holidays of the Netherlands. There are 2 official rules (_Het Groene Boekje_ and _Het Witte Boekje_) that may be used to determine whether both letters should be written in capital. I used the most common rule, because this looks nicer in my opinion.
> Corrected Dutch Easter holiday names

- Src/Nager.Date/PublicHolidays/AustriaProvider.cs
10-26 is called Nationalfeiertag while 01-05 is called Staatsfeiertag. Source: https://en.wikipedia.org/wiki/Public_holidays_in_Austria
Thanks for the library.
> Change Austrians 10-26 to 'Nationalfeiertag'

- Src/Nager.Date.UnitTest/Country/UnitedKingdomTest.cs
- Src/Nager.Date/PublicHolidays/UnitedKingdomProvider.cs
* Fixed Christmas Day and Boxing Day date handling for scenarios where Christmas Day is a Sunday, or Boxing Day is a Saturday.
Substitute days should now be as below:
Scenario 1: Christmas Day on Saturday and Boxing Day on Sunday (see 2021)
- Christmas Day has a substitute day of the following Monday.
- Boxing Day has a substitute day of the following Tuesday.
Scenario 2: Christmas Day on Sunday, Boxing Day on Monday (see 2016)
- Christmas Day has a substitute day of the following Tuesday.
- Boxing Day remains unchanged.
Scenario 3: Christmas Day on Friday, Boxing Day on Saturday (see 2020)
- Christmas day remains unchanged.
- Boxing Day has a substitute day of the following Monday.
Reference for the three scenarios: https://web.archive.org/web/20200624132154/https://www.gov.uk/bank-holida …
> Fixed Christmas Day and Boxing Day bank holidays

- Src/Nager.Date/PublicHolidays/CroatiaProvider.cs
In 2020 there was a change in holidays: June 25 (Statehood Day) and October 8 (Independence Day) were demoted from public holidays to memorial days, and May 30 (National Day) and November 18 (Remembrance Day) were promoted from memorial days to public holidays.
> Croatia 2020 Remembrance Day addition and Independece Day exclusion

- Src/Nager.Date.UnitTest/Country/SwedenTest.cs
- Src/Nager.Date/PublicHolidays/SwedenProvider.cs
This fix is not a big thing since the current logic works fine for the last 15 years, today and in the foreseeable future. But this fix corrects a historical incorrectness.
Sweden haven't had the National Day as a public holiday forever. Historically, Pentecost Monday (not sure this is what it is called in English, in Swedish it is "Annandag Pingst") used to be a public holiday instead but those two were exchanged starting by the year 2005 to follow the current logic.
I didn't find this information on the English Wikipedia page (yeah, oddly enough they don't keep track of all the tiny Swedish calendar details...) but it can be verified by google translate the Swedish Wikipedia page: https://sv.wikipedia.org/wiki/Sveriges_nationaldag.
> Added logic for when Sweden switched National Day to be a public holiday

- Src/Nager.Date/PublicHolidays/SpainProvider.cs
Maundy Thursday was incorrectly calculated (was the same as Holy Friday)
> Fix for Maundy Thursday (Jueves Santo) in Spain

- README.md
- Src/Nager.Date/DateSystem.cs
- Src/Nager.Date/Nager.Date.csproj
As previously discussed, here is the remove of the `DateSystem.GetAge` method as well as the Version Bump with Release Notes.
> Removed get age

- Src/Nager.Date.UnitTest/Country/SpainTest.cs
- Src/Nager.Date/PublicHolidays/SpainProvider.cs
Add Catalonia regional holiday "Sant Esteve" using https://en.wikipedia.org/wiki/Public_holidays_in_Spain as source
> Add Catalonia regional holiday "Sant Esteve"

- CHANGELOG.md
- Src/Nager.Date/DateSystem.cs
- Src/Nager.Date/Nager.Date.csproj
- Src/Nager.Date/PublicHolidays/MontenegroProvider.cs
https://en.wikipedia.org/wiki/Public_holidays_in_Montenegro
The religious holidays for Muslim and Jewish are not included
> Add Montenegro

- Src/Nager.Date/PublicHolidays/CanadaProvider.cs
New-Brunswick is celebrating Family Day but it was missing in the list.
- https://www2.gnb.ca/content/gnb/en/departments/elg/local_government/content/governance/content/days_of_rest_act.html
- https://en.wikipedia.org/wiki/Public_holidays_in_Canada
> Added New-Brunswick in Family Day holiday

- Src/Nager.Date/PublicHolidays/CostaRicaProvider.cs
- Fix Costa Rica holidays
Cultures National Day no longer a holiday, it was replaced with the Army Abolition Day
- Fix names and add local names
> Fix Costa Rica public holidays

- src/Nager.Date/PublicHolidays/FinlandProvider.cs
Small adjustments for Finnish translations. In Finland we do not use 2. format if
number is lower than 10. Also Tapaninpäivä is more commonly used here.
> Make betterr translations for Finnish

- src/Nager.Date.UnitTest/Country/IsleOfManTest.cs
- src/Nager.Date/PublicHolidays/IsleOfManProvider.cs
The current bank holidays are fairly basic and don't line up with the actual observed holidays.
Amended bank holidays to shift at weekends and added adjustments for VE Day & Queen Jubilee.
Most of the holidays follow similar rules to UK so are mostly copied from the UK provider.
Renamed 'Labour Day' to 'Early May Bank Holiday' in line with the gov.im page
https://www.gov.im/categories/home-and-neighbourhood/bank-holidays/
Also added in tests for most bank holidays since 2015 based on data from [Wayback Machine](https://web.archive.org/web/20150316155431/http://www.gov.im/categories/home-and-neighbourhood/bank-holidays/)
> Fix Isle of Man Bank Holidays

- src/Nager.Date/PublicHolidays/FaroeIslandsProvider.cs
Faroese Translation for General Prayer Day (Store Bededag). See Wikipedia article for documentation.
> FaroeIslandsProvider: Faroese translation for General Prayer Day.

- src/Nager.Date.UnitTest/Country/UnitedKingdomTest.cs
- src/Nager.Date/PublicHolidays/UnitedKingdomProvider.cs
Affected country
United Kingdom
Affected public holiday
Queens State Funeral
Source of the information
[https://www.gov.uk/government/news/bank-holiday-announced-for-her-majesty-queen-elizabeth-iis-state-funeral-on-monday-19-september](https://www.gov.uk/government/news/bank-holiday-announced-for-her-majesty-queen-elizabeth-iis-state-funeral-on-monday-19-september)
More Information
Added Queen's state funeral following pattern for adding Queen's Platinum Jubilee
> Add Queen's state funeral as a public holiday

- src/Nager.Date/PublicHolidays/BulgariaProvider.cs
Fixed Bulgarian holidays where Latin C is used instead of Bulgarian Cyrillic С (S).
If this looks confusing, [check this to see the difference](https://translate.google.com/?hl=en&tab=TT&sl=bg&tl=en&text=C%0A%D0%A1&op=translate).
> Fix Bulgarian Cyrillic C

- src/Nager.Date.UnitTest/Country/UnitedKingdomTest.cs
- src/Nager.Date/PublicHolidays/UnitedKingdomProvider.cs
UK just announced new bank holiday for the coronation of King Charles III
https://www.gov.uk/government/news/bank-holiday-proclaimed-in-honour-of-the-coronation-of-his-majesty-king-charles-iii
https://www.bbc.co.uk/news/uk-63528830
> United Kingdom

- src/Nager.Date.UnitTest/Country/IsleOfManTest.cs
- src/Nager.Date/PublicHolidays/IsleOfManProvider.cs
https://www.gov.im/categories/home-and-neighbourhood/bank-holidays/
https://www.iomtoday.co.im/news/extra-bank-holiday-to-mark-king-charles-iiis-coronation-571967
The past holiday 19/09/2022 was missing and the upcoming 08/05/2023 was added to be observed by Isle of Man as well.
> Isle of Man - Missing Royal Holidays

- src/Nager.Date.UnitTest/Common/LogicTest.cs
- src/Nager.Date/PublicHolidays/AustraliaProvider.cs
- src/Nager.Date/PublicHolidays/BosniaAndHerzegovinaProvider.cs
Hey, 
I was looking through holidays and I've noticed that ISO 3166-2 codes for two of the countries Australia and 
Bosnia And Herzegovina are incorrect inside of Public Holidays. 
I've corrected them using codes specified in wikipedia for [Australia](https://en.wikipedia.org/wiki/ISO_3166-2:AU) and [Bosnia and Herzegovina](https://en.wikipedia.org/wiki/ISO_3166-2:BA). 
I was also considering adding [Brčko distrikt (BA-BRC)](https://en.wikipedia.org/wiki/Br%C4%8Dko_District) to the list of counties, but decided against it as [BAH wikipedia holiday page](https://en.wikipedia.org/wiki/Public_holidays_in_Bosnia_and_Herzegovina) does not state anything about holidays in that district. 
Let me know what you think.
Thanks!
> fix: incorrect counties for Australia and Bosnia And Herzegovina 

- src/Nager.Date/PublicHolidays/AustraliaProvider.cs
Updated Boxing day shift and added Christmas day shift for Australia.
If Christmas is on a weekend it should be shifted to the 27th
If Boxing day is on a weekend it should be shifted to the 28th
Examples can be found here: https://data.gov.au/dataset/ds-dga-b1bc6077-dadd-4f61-9f8c-002ab2cdff10/details?q=
> Australia - Fix Christmas and Boxing Day Weekend Shift

- src/Nager.Date/PublicHolidays/CanadaProvider.cs
BC Day was mistakenly named as civic holiday. 
Issue #539
> Canada - Fix British Columbia Day

- src/Nager.Date/PublicHolidays/SingaporeProvider.cs
https://github.com/nager/Nager.Date/issues/568
> Singapore - Fix Chinese New Year sunday shift

- src/Nager.Date/PublicHolidays/SingaporeProvider.cs
The Deepavali day is mismatched: 
- Expected day: Oct 31 2024
- Actual day: Nov 1 2024
Source: https://www.mom.gov.sg/newsroom/press-releases/2023/0524-public-holidays-for-2024
> Singapore - Fix Deepavali Day

- README.md
There is no generally valid designation for the next administrative level of countries.
"Nager.Date" supports the initial subdivision of a country, but we will not support a detailed level because the effort required is too high.
> Update README SubdivisionCodes

- src/Nager.Date/HolidayProviders/UnitedKingdomHolidayProvider.cs
The second holiday of the year in Scotland is not called "New Year's Day", the closest it has to a name is plain "2 January".
https://www.mygov.scot/scotland-bank-holidays
> Rename Scotland 2 january holiday

- src/Nager.Date.UnitTest/Countries/MoroccoTest.cs
- src/Nager.Date/HolidayProviders/MoroccoHolidayProvider.cs
Morocco has stated January the 14th as an official paid public holiday, starting from 2024.
Read more here https://www.moroccoworldnews.com/2023/08/356893/moroccan-government-sets-amazigh-new-years-official-date-on-january-14
> Support Morocco Amazigh new year starting from 2024

- src/Nager.Date/HolidayProviders/UnitedStatesHolidayProvider.cs
https://github.com/nager/Nager.Date/issues/430
> United States - Fix Indigenous Peoples' Day

- src/Nager.Date/HolidayProviders/MexicoHolidayProvider.cs
- src/Nager.Date/HolidaySystem.cs
https://github.com/nager/Nager.Date/issues/632
> Mexico - Add Holy Thursday and Good Friday

- src/Nager.Date/HolidayProviders/UnitedKingdomHolidayProvider.cs
- https://www.gov.uk/bank-holidays#england-and-wales
> If a bank holiday is on a weekend, a ‘substitute’ weekday becomes a bank holiday, normally the following Monday.
- https://www.gov.scot/publications/bank-holidays/
> United Kingdom - Fix missing ObservedRuleSets

- src/Nager.Date/HolidayProviders/UkraineHolidayProvider.cs
Changes to Ukraine Holidays
Victory Day over Nazism in World War II changed to 03.08 starting from 2024 Deleted Julian Christmas starting from 2024
Changed Defender of Ukraine Day dates to be accurate from 2015 to 2023 and from 2023 onward. All new dates are inline with original source https://en.wikipedia.org/wiki/Public_holidays_in_Ukraine
> Update to Ukrainian holidays in UkraineHolidayProvider.cs

- src/Nager.Date/HolidayProviders/ArgentinaHolidayProvider.cs
- https://github.com/nager/Nager.Date/issues/685
I have incorporated the logic that holidays on Tuesday or Wednesday are moved to the previous Monday. Holidays on Thursday, Friday, Saturday, Sunday are moved to the following Monday. 
As described on https://en.wikipedia.org/wiki/Public_holidays_in_Argentina.
@JuanIgnacioPayo
But the described rules do not match with the “General José de San Martín Memorial Day”?
> Argentina - Fix Weekday shift logic

- src/Nager.Date/HolidayProviders/VenezuelaHolidayProvider.cs
- https://github.com/nager/Nager.Date/issues/705
> Venezuela - Fix HolidayTypes

- src/Nager.Date/HolidayProviders/GermanyHolidayProvider.cs
LiberationDay is an holiday in berlin in 2025 once:
Source: https://www.berlin.de/aktuelles/9188766-958090-einmaliger-feiertag-am-8-mai-2025.html#:~:text=%C2%ABOrt%20der%20Kapitulation%C2%BB%20steht%20auf,in%20Berlin%20zum%20gesetzlichen%20Feiertag.
> Holiday - Germany - Berlin - LiberationDay 2025

- src/Nager.Date/HolidayProviders/DominicanRepublicHolidayProvider.cs
- src/Nager.Date/HolidayProviders/ElSalvadorHolidayProvider.cs
- src/Nager.Date/HolidayProviders/PuertoRicoHolidayProvider.cs
Changes:
- Puerto Rico - Some holiday names have alternative titles that were not separated by `/`. Added this as it seemed like proper convention.
- Dominican Republic - Added local names for holidays that were still in English. These were sourced to the best of my abilities from reading articles to the names that they use but I'm open for corrections.
- El Salvador - Uppercased letter as it seemed like convention. Other "Día del Trabajo" exist in the codebase with the new capitalization.
As for the Puerto Rico local names, some of these holidays that have alternative names I've never heard anyone use as a Puerto Rican myself that's lived all my life here. I don't know if you would be open for changes to these.
> Fix local names for some Puerto Rico, Dominican Republic, and El Salvador holidays

- src/Nager.Date/HolidayProviders/AustraliaHolidayProvider.cs
- https://github.com/nager/Nager.Date/issues/720
> Australia - Fix Friday before AFL Grand Final for 2024

- src/Nager.Date/HolidayProviders/GermanyHolidayProvider.cs
https://pardok.parlament-berlin.de/starweb/adis/citat/VT/19/gvbl/g24280460.pdf
Another public holiday on June 17, 2028
In 2028, Berliners will have another unique public holiday: June 17. The occasion is the 75th anniversary of the popular uprising in the GDR. During the uprising on June 17, 1953, over one million people in the GDR took part in largely peaceful protests, strikes and demonstrations. The uprising was violently suppressed.
- https://github.com/nager/Nager.Date/issues/723
> Germany - Add Uprising of June 17 1953

- .github/dependabot.yml
- .github/workflows/dotnet.yml
The PR extends the functionality beyond the EcoSystem `nuget`, so that we will also receive dependency updates for `GitHub-Actions` in the future.
In addition, the PR build pipeline has been extended so that an additional step is now performed in the case of `dependabot[bot]` pull requests, which automates these PRs `merged` based on the configurations.
@tinohager For this to work properly, you would need to provide a `Dependabot Secret` with the name `DEPENDABOT`. A GITHUB_TOKEN should be used as the content, which receives the necessary authorizations for the authorization of the merge. For more information about [DependaMerge](https://github.com/dailydevops/dependamerge-action/) please read here.
> chore: Extend Dependabot Support

- src/Nager.Date/HolidayProviders/UnitedStatesHolidayProvider.cs
The most important changes are the addition of Truman Day and Lincoln's Birthday to the holiday specifications.
New holiday specifications:
* Added Truman Day on May 8th to the list of holidays, which is observed in Missouri and categorized under authorities and school holidays.
* Added a new method `LincolnsBirthday` to define Lincoln's Birthday on February 12th, observed in multiple states and categorized as an observance holiday.
> United States - Add Truman Day and Lincoln's Birthday

- src/Nager.Date/HolidayProviders/PhilippinesHolidayProvider.cs
Adding Philippine Regular and Special (Non-Working) Holidays pursuant to Proclamation 727 
Reference:
https://www.officialgazette.gov.ph/downloads/2024/10oct/20241030-PROC-727-FRM.pdf
> add PhilippinesHolidayProvider.cs

- src/Nager.Date/HolidayProviders/SloveniaHolidayProvider.cs
Add day of Primož Trubar and fix 25th September to sovereignty day instead of sport day
> Slovenia - Add Primož Trubar Day and fix Sovereignty Day

- src/Nager.Date/HolidayProviders/TunisiaHolidayProvider.cs
Hello,
This PR fixes few wrong dates in the Tunisian Holidays Calendar while adding the translations from the official language (Arabic)
While there are also other religious holidays such as Eid al-Fitr or Eid al-Adha... the dates for these holidays are always tentative and determined just few days before the actual holiday based on the lunar calendar.
For now, there is no way to automatically extract the actual date since this data is not published ONLINE by some official (and reliable) government entity (they are usually web articles...)
> Tunisia - Fix Holidays LocalName and Revolution Day

- src/Nager.Date/HolidayProviders/GermanyHolidayProvider.cs
This PR removes Pentecost Sunday (Pfingstsonntag) as a public holiday in the state of Hesse. It was incorrectly listed, despite never having been a holiday in Hesse. All occurrences of this holiday in Hesse have been removed to reflect the correct legal status. Pentecost Sunday is only recognized as a public holiday in Brandenburg.
Official list of public holidays in the federal state of Hesse: https://innen.hessen.de/buerger-staat/feiertage
Fix #791
> Removed Pentecost Sunday as public holiday in Hesse

- src/Nager.Date/HolidayProviders/RepublicOfCongoHolidayProvider.cs
- src/Nager.Date/HolidaySystem.cs
**Feature**: Add holiday provider for the Republic of Congo  
**Related issue**: #795 
- Added a new `RepublicOfCongoHolidayProvider` implementing all known public holidays.  
- Included official national holidays and common observances.  
- Ensured consistency with other holiday providers.
> Republic of Congo - Feat add all Holiday

- src/Nager.Date/HolidayProviders/DemocraticRepublicOfCongoHolidayProvider.cs
- src/Nager.Date/HolidaySystem.cs
This PR introduces a new holiday provider for the Democratic Republic of the Congo. It includes the following fixed-date public holidays, based on [Wikipedia's list](https://en.wikipedia.org/wiki/Public_holidays_in_the_Democratic_Republic_of_the_Congo):
- January 1 – New Year's Day  
- January 4 – Martyrs' Day  
- January 16 – Laurent-Désiré Kabila Assassination  
- January 17 – Patrice Lumumba Assassination  
- April 6 – Kimbangu's Day  
- May 1 – Labour Day  
- May 17 – Liberation Day & Armed Forces Day  
- June 30 – Independence Day  
- August 1 – Parents' Day  
- August 2 – Congolese Genocide Day  
- November 1 – All Saints' Day  
- December 25 – Christmas Day  
- Corrected the country code from `CG` to `CD`
- Removed duplicate entries
- Improved formatting and consistency with other …
> 🇨🇩 Add Holiday Provider for Democratic Republic of the Congo (CD)

- src/Nager.Date/HolidayProviders/AustraliaHolidayProvider.cs
This pull request updates the holiday specifications in the `AustraliaHolidayProvider` class to reflect a more accurate naming for a specific public holiday in South Australia.
* [`src/Nager.Date/HolidayProviders/AustraliaHolidayProvider.cs`](diffhunk://#diff-eb939e35f57a60e0b853d7429b45ea62a443d8d480e61c46f18a6bb329ccc39aL96-R97): Renamed the holiday on the second Monday in March from "March Public Holiday" to "Adelaide Cup Day" in both `EnglishName` and `LocalName` fields.
- https://github.com/nager/Nager.Date/issues/555
> Australia - Fix Adelaide Cup Day naming

- src/Nager.Date/HolidayProviders/ItalyHolidayProvider.cs
This pull request updates the `ItalyHolidayProvider` class in the `Nager.Date` library to implement subdivision codes functionality. The changes include adding the `ISubdivisionCodesProvider` interface and implementing a method to provide Italian subdivision codes.
* [`src/Nager.Date/HolidayProviders/ItalyHolidayProvider.cs`](diffhunk://#diff-e30f9443f23cee4424adb94dd00aaafffbc0375a6cfa68af26c8d9d74c72f104L11-R11): Updated the `ItalyHolidayProvider` class to implement the `ISubdivisionCodesProvider` interface, enabling the retrieval of Italian subdivision codes. Added the `GetSubdivisionCodes` method to return a dictionary mapping subdivision codes (e.g., "IT-65") to their corresponding names (e.g., "Abruzzo"). [[1]](diffhunk://#diff-e30f9443f23cee4424adb94dd00aaafffbc0375a6cfa68af26c8d9d7 …
> Italy - Add subdivision codes

- src/Nager.Date/HolidayProviders/UnitedStatesHolidayProvider.cs
Previously the English name was "Labor," but this was changed recently to reflect the English spelling. The LocalName was incorrectly "Labour," but it should have the local spelling of "Labor."
https://en.wikipedia.org/wiki/Public_holidays_in_the_United_States
> Fix local name spelling of 'Labour Day' to 'Labor Day' for US holiday
