Nager.Date/Data/DataIT.cs
It was set on the same day of Christmas, instead of December 26th.
Anyway, thank you for your really useful library.
=> Fixed St. Stephen's Day for Italy

README.md
It should use CountryCode enum instead of string
=> Correct IsPublicHoliday example in README

Nager.Date/PublicHolidays/BulgariaProvider.cs, Nager.Date/PublicHolidays/GreeceProvider.cs, Nager.Date/PublicHolidays/RomaniaProvider.cs
=> Mark Romania, Bulgaria and Greece as Orthodox

Src/Nager.Date/PublicHolidays/RussiaProvider.cs
Hi Tino, I just found a bit of time and fixed Russian translation for holidays as spoken for a long ago.
=> Fix translation for International Women's Day

Src/Nager.Date/PublicHolidays/NewZealandProvider.cs
Same calculation as is used for boxing day further down the file.
=> Fix day after New Years calculation

Src/Nager.Date/PublicHolidays/BrazilProvider.cs
added non fixed holidays (easter, carnival, passion of jesus and corpus christi) with calculations, sorry about any misconducts, it's my first contribution to any github project.
Reference in http://hernaski.com.br/blog/calcular-data-de-pascoa-e-carnaval-em-c/5 from Mauricio Hernaski
=> Added non fixed holidays for Brazil

Src/Nager.Date/PublicHolidays/CanadaProvider.cs
RE: https://github.com/tinohager/Nager.Date/issues/62
=> Added Ontario to Civic Holiday

Src/Nager.Date/PublicHolidays/BelgiumProvider.cs
https://github.com/tinohager/Nager.Date/issues/81
=> Belgium holidays: Dutch vs French/German languages

Src/Nager.Date/PublicHolidays/GermanyProvider.cs
Add lower saxony to counties string array of the reformation day
Fix #86
=> [Germany Provider] Lower Saxony - Reformation Day

Src/Nager.Date/PublicHolidays/TunisiaProvider.cs
Remove entries dependence moon calendar
=> Update tunisia provider

README.md
Fix typo and update the supported countries count in *alternative projects*
=> Update alternative projects in README.md

Src/Nager.Date/PublicHolidays/SpainProvider.cs
It's on March 19th, not March 1st. See [here](https://www.diafestivo.es/san-jose.php).
=> Correct St. Joseph's Day in Spain

Src/Nager.Date/PublicHolidays/UnitedKingdomProvider.cs
=> Add counties to UnitedKingdomProvider

Src/Nager.Date.UnitTest/Country/UnitedKingdomTest.cs, Src/Nager.Date/PublicHolidays/UnitedKingdomProvider.cs
Edited May 2020 UK Code and added test over functionality.
Fixes #153.
=> Edited UK May Day 2020 code and added test - Fixes #153.

Src/Nager.Date.UnitTest/Common/LogicTest.cs, Src/Nager.Date/DateSystem.cs, Src/Nager.Date/PublicHolidays/FinlandProvider.cs
Fix Finland holidays for All Saints' Day
=> Fix Finland holidays for All Saints' Day

Src/Nager.Date/PublicHolidays/EstoniaProvider.cs, Src/Nager.Date/PublicHolidays/SwedenProvider.cs
Fix for Estonia's Finno-Ugrian Days/Ethnicity day and Sweden's Pentecost Sunday
=> Fix for Sweden's Pentecost Sunday

Src/Nager.Date/DateSystem.cs
https://en.wikipedia.org/wiki/Workweek_and_weekend#Friday_weekend_(One_day_weekend)
=> Fix Iran's weekend provider

Src/Nager.Date.UnitTest/Country/GermanyTest.cs, Src/Nager.Date/PublicHolidays/GermanyProvider.cs
=> Add 'Liberation Day' 2020-05-08 for Germany/Berlin

Src/Nager.Date.UnitTest/Common/CountryTest.cs, Src/Nager.Date/DateSystem.cs
=> Add IsPublicHoliday(DateTime date, string countryCode) to DateSystem.cs

Src/Nager.Date.UnitTest/Country/PapuaNewGuineaTest.cs, Src/Nager.Date/DateSystem.cs, Src/Nager.Date/PublicHolidays/PapuaNewGuineaProvider.cs
Source: https://en.wikipedia.org/wiki/Public_holidays_in_Papua_New_Guinea
=> Add PapuaNewGuinea

Src/Nager.Date/DateSystem.cs, Src/Nager.Date/PublicHolidays/GibraltarProvider.cs
https://en.wikipedia.org/wiki/Public_holidays_in_Gibraltar
=> Add Gibraltar

Src/Nager.Date/DateSystem.cs, Src/Nager.Date/PublicHolidays/MontserratProvider.cs
https://en.wikipedia.org/wiki/Public_holidays_in_Montserrat
=> Add Montserrat

CHANGELOG.md, Src/Nager.Date/PublicHolidays/AustraliaProvider.cs
https://github.com/nager/Nager.Date/issues/225
=> Fix Australia Weekend Shift

CHANGELOG.md, Src/Nager.Date/PublicHolidays/CanadaProvider.cs
https://github.com/nager/Nager.Date/issues/245
=> Fix FamilyDay Canada

Src/Nager.Date/PublicHolidays/CanadaProvider.cs
According to Wikipedia Victoria Day is a "global" Federal holiday
=> Canada Victoria day is country-wide

Src/.editorconfig, Src/Nager.Date.TestConsole/Program.cs, Src/Nager.Date.sln, Src/Nager.Date/DateSystem.cs
To ensure consistent CodeStyle and automatic support for Visual Studio and other IDEs, we added an .editorconfig.
=> Added .editorconfig

Src/Nager.Date.UnitTest/Country/DenmarkTest.cs, Src/Nager.Date/DateSystem.cs
This should solve the problem described in #263.
=> Fixed #263, exclude bank, school and other types of holidays

CHANGELOG.md, Src/Nager.Date/PublicHolidays/JapanProvider.cs
=> Updated the Emperors Day and added historical values.

CHANGELOG.md, Src/Nager.Date/DateSystem.cs, Src/Nager.Date/Model/PublicHoliday.cs, Src/Nager.Date/PublicHolidays/NigeriaProvider.cs
=> Added Nigeria as PublicHoliday Provider

Src/.editorconfig, Src/Nager.Date.Website/Controllers/ApiController.cs
Added more rules to the editorconfig for `this.`, to further support our code standard.
=> Updated Editorconfig

Src/Nager.Date.UnitTest/Common/LogicTest.cs, Src/Nager.Date/PublicHolidays/GermanyProvider.cs
=> Added Easter Sunday and Pentecost for Brandenburg and Hesse

Src/Nager.Date/Contract/LongWeekendCalculator.cs
https://github.com/nager/Nager.Date/issues/280
=> Consider only global holidays for the long weekend calculation

Src/Nager.Date.UnitTest/Common/LongWeekendTest.cs, Src/Nager.Date/Contract/LongWeekendCalculator.cs
=> Fix sub dependencies long weekend

Src/Nager.Date/Model/PublicHoliday.cs, Src/Nager.Date/PublicHolidays/BahamasProvider.cs
=> Added shifting rules for bahamas provider

Src/Nager.Date/DateSystem.cs, Src/Nager.Date/PublicHolidays/UnitedStatesProvider.cs
fix #273
Based on the information of the link https://www.timeanddate.com/holidays/us/good-friday
=> Added Goodfriday to US Provider

Src/Nager.Date/PublicHolidays/GermanyProvider.cs
Fix https://github.com/nager/Nager.Date/issues/282#issuecomment-849950208
=> Fix Germany/Easter Sunday

Src/Nager.Date/PublicHolidays/NetherlandsProvider.cs
https://github.com/nager/Nager.Date/issues/298
=> Netherlands - Fix local translation Good Friday

Src/Nager.Date/PublicHolidays/UnitedStatesProvider.cs
https://github.com/nager/Nager.Date/issues/299
=> UnitedStates - Add Juneteenth

Src/Nager.Date/PublicHolidays/NetherlandsProvider.cs
=> Add Pentecost to list of public holidays

Src/Nager.Date/PublicHolidays/ChileProvider.cs
I created a question before, now i look this link: https://en.wikipedia.org/wiki/Public_holidays_in_Chile
=> parameters added to Battle of Arica item

Src/Nager.Date/PublicHolidays/SwitzerlandProvider.cs
Fix for https://github.com/nager/Nager.Date/issues/322
=> Switzerland fix Federal Day of Thanksgiving

src/Nager.Date.UnitTest/DateTimeExtension/DateTimeExtension_ShiftToClosest.cs, src/Nager.Date/Extensions/DateTimeExtension.cs, src/Nager.Date/PublicHolidays/NewZealandProvider.cs
=> NZ regional holidays

src/Nager.Date/PublicHolidays/CanadaProvider.cs
Add new canadian holiday as per #325
It's my first contribution to an open source repository, I'm open to any feedback 😄
=> [CANADA] Issue #325 - Add National Day for Truth and Reconciliation

src/Nager.Date/PublicHolidays/BulgariaProvider.cs
https://github.com/nager/Nager.Date/issues/365
https://github.com/nager/Nager.Date/issues/369
=> Bulgaria Incorrect Public Holiday 

src/Nager.Date.UnitTest/Country/JapanTest.cs, src/Nager.Date/PublicHolidays/JapanProvider.cs
https://github.com/nager/Nager.Date/issues/371
=> Japan fix for AutumnalEquinox and VernalEquinox

src/Nager.Date.UnitTest/Country/BrazilTest.cs, src/Nager.Date/PublicHolidays/BrazilProvider.cs
Add a test class for BrazilProvider and a state of Sao Paulo holiday.
=> Fix Brazilian Holiday

src/Nager.Date/PublicHolidays/GreenlandProvider.cs
Fix for issue 381:
https://github.com/nager/Nager.Date/issues/381
Added missing holidays and translations for Greenland.
=> GreenlandProvider: Added translations and missing holidays: #381

src/Nager.Date/PublicHolidays/SpainProvider.cs
Spain - Updated regions, removed provinces
=> Spain - Updated regions, removed provinces

src/Nager.Date.UnitTest/Country/SpainTest.cs, src/Nager.Date/PublicHolidays/SpainProvider.cs
https://github.com/nager/Nager.Date/issues/398
=> Add Santiago Apostol to spain

src/Nager.Date.UnitTest/Country/SpainTest.cs, src/Nager.Date/PublicHolidays/SpainProvider.cs
https://github.com/nager/Nager.Date/issues/400
=> Fix san jose calculation

src/Nager.Date/PublicHolidays/SpainProvider.cs
https://github.com/nager/Nager.Date/issues/401
=> Spain add Whit Monday for ES-CT

src/Nager.Date.UnitTest/Country/SpainTest.cs, src/Nager.Date/PublicHolidays/SpainProvider.cs
https://github.com/nager/Nager.Date/issues/399
=> Spain - Fix christmas day for 2022

src/Nager.Date/DateSystem.cs, src/Nager.Date/PublicHolidays/AlbaniaProvider.cs
I added catholic Easter and Easter monday to Albania,
and renamed Easter monday "Hënen e Pashkët" to emphasize the difference.
Translation is from Google I have no knowledge in albanian language.
=> Added catholic Easter to Albania

src/Nager.Date/DateSystem.cs, src/Nager.Date/PublicHolidays/AndorraProvider.cs
Except Carnaval (date unknown)
Corrected National Holiday date
=> Added missing holidays to Andorra (wikipedia source)

src/Nager.Date.UnitTest/Country/TurkeyTest.cs, src/Nager.Date/DateSystem.cs, src/Nager.Date/PublicHolidays/TurkeyProvider.cs
=> Added Turkey Feast of Ramadan & Feast of Eid Holidays

src/Nager.Date/PublicHolidays/ChileProvider.cs
https://github.com/nager/Nager.Date/issues/442
=> Fix NationalPlebiscite only 2022

src/Nager.Date/PublicHolidays/CanadaProvider.cs
https://github.com/nager/Nager.Date/issues/452
=> Add Saskatchewan Day, optimize naming for Boxing Day

src/Nager.Date/PublicHolidays/IrelandProvider.cs
https://github.com/nager/Nager.Date/issues/448
=> Ireland - Add Saint Brigid's Day

src/Nager.Date.UnitTest/Country/ColombiaTest.cs, src/Nager.Date/PublicHolidays/ColombiaProvider.cs
- Saint Joseph's Day
- Ascension Day
- Assumption of Mary
- Independence of Cartagena
https://github.com/nager/Nager.Date/issues/360
=> Colombia - Fix monday shift for some holidays

src/Nager.Date.UnitTest/Country/SouthAfricaTest.cs, src/Nager.Date/PublicHolidays/SouthAfricaProvider.cs
https://github.com/nager/Nager.Date/issues/446
=> South Africa - Fix missing holiday shift

src/Nager.Date/Extensions/ListExtension.cs, src/Nager.Date/PublicHolidays/CanadaProvider.cs, src/Nager.Date/PublicHolidays/SpainProvider.cs
https://github.com/nager/Nager.Date/issues/435
=> Spain - Adjustments for 2023

src/Nager.Date/PublicHolidays/AustraliaProvider.cs
https://github.com/nager/Nager.Date/pull/468
=> Australia - Optimize LabourDay

src/Nager.Date/PublicHolidays/RomaniaProvider.cs
https://github.com/nager/Nager.Date/issues/474
=> Romania - Epiphany and Saint John the Baptist

src/Nager.Date/PublicHolidays/DenmarkProvider.cs
https://github.com/nager/Nager.Date/issues/469
=> Denmark - General Prayer Day 2024

src/Nager.Date/PublicHolidays/AustraliaProvider.cs
https://github.com/nager/Nager.Date/issues/477
=> Australia - Fix Monarch birthday name

src/Nager.Date/PublicHolidays/BulgariaProvider.cs
I have added the weekend move logic can you please check it out
https://github.com/nager/Nager.Date/issues/481
=> Bulgaria - Add weekend shift logic

src/Nager.Date/PublicHolidays/LiechtensteinProvider.cs
https://github.com/nager/Nager.Date/issues/489
=> Liechtenstein - Fix Ascension Day

src/Nager.Date/PublicHolidays/LiechtensteinProvider.cs
https://github.com/nager/Nager.Date/issues/491
=> Liechtenstein - Fix Bank Holidays

CHANGELOG.md, src/Nager.Date/PublicHolidays/NetherlandsProvider.cs
https://github.com/nager/Nager.Date/issues/497
=> Netherlands - Fix WhitMonday local translation

CHANGELOG.md, src/Nager.Date/PublicHolidays/GermanyProvider.cs
https://github.com/nager/Nager.Date/issues/500
=> Germany - Fix World Childrens Day show before 2019

CHANGELOG.md, src/Nager.Date/PublicHolidays/BelgiumProvider.cs
https://github.com/nager/Nager.Date/issues/513
=> Belgium - Add bank holidays

CHANGELOG.md, src/Nager.Date/PublicHolidays/NewZealandProvider.cs
https://github.com/nager/Nager.Date/issues/511
=> New Zealand - Fix King birthday

src/Nager.Date/PublicHolidays/ColombiaProvider.cs
Fix Holiday translation
https://github.com/nager/Nager.Date/issues/523
Remove Carnival only valid in the city of Barranquilla
https://github.com/nager/Nager.Date/issues/524
=> Colombia - Fix Carnival and Battle of Boyacá

src/Nager.Date/PublicHolidays/ZimbabweProvider.cs
https://github.com/nager/Nager.Date/issues/521
=> Zimbabwe - Fix Defence Forces Day

src/Nager.Date/PublicHolidays/ChileProvider.cs
https://github.com/nager/Nager.Date/issues/485
=> Chile - Fix National Day of Indigenous Peoples

src/Nager.Date/PublicHolidays/SingaporeProvider.cs
https://github.com/nager/Nager.Date/issues/532
=> Singapore - Polling Day

src/Nager.Date/PublicHolidays/SloveniaProvider.cs
https://github.com/nager/Nager.Date/issues/526
=> Slovenia - Solidarity day

CHANGELOG.md, src/Nager.Date/PublicHolidays/JapanProvider.cs
https://github.com/nager/Nager.Date/issues/547
=> Japan - Fix Health and Sports Day

CHANGELOG.md, src/Nager.Date/PublicHolidays/AustraliaProvider.cs
https://github.com/nager/Nager.Date/issues/546
=> Australia - Fix King's Birthday Queensland

CHANGELOG.md, src/Nager.Date/PublicHolidays/AustraliaProvider.cs
https://github.com/nager/Nager.Date/issues/543
=> Australia - Fix New Year's Day weekend shift

src/Nager.Date/PublicHolidays/SouthAfricaProvider.cs
Issue: https://github.com/nager/Nager.Date/issues/559
=> South Africa - Add Springboks Victory 2023

src/Nager.Date/PublicHolidays/AustraliaProvider.cs
Issue: https://github.com/nager/Nager.Date/issues/552
=> Australia - Fix missing Melbourne Cup

src/Nager.Date/PublicHolidays/AlandProvider.cs
https://github.com/nager/Nager.Date/issues/583
=> Åland - Remove some holidays

src/Nager.Date/PublicHolidays/MexicoProvider.cs
https://github.com/nager/Nager.Date/issues/584
=> Mexico - Fix Inauguration Day 2024

src/Nager.Date/PublicHolidays/LiechtensteinProvider.cs
Add Shrove Tuesday. Type Bank. Solves: https://github.com/nager/Nager.Date/issues/591
=> Patch - Liechtenstein Holidays

src/Nager.Date/HolidayProviders/HongKongHolidayProvider.cs, src/Nager.Date/HolidaySystem.cs
migrate existing code
https://github.com/nager/Nager.Date/pull/262
=> Add Hong Kong HolidayProvider

src/Nager.Date.UnitTest/Country/AlbaniaTest.cs, src/Nager.Date/HolidayProviders/AlbaniaHolidayProvider.cs
- Fix some holidays for Albania
- Add test for Albania
=> Working on Albanian Holidays

src/Nager.Date/HolidayProviders/KazakhstanHolidayProvider.cs, src/Nager.Date/HolidaySystem.cs
=> Add Kazakhstan

src/Nager.Date/HolidayProviders/GeorgiaHolidayProvider.cs, src/Nager.Date/HolidaySystem.cs
=> Add Georgia

src/Nager.Date/HolidayProviders/ArmeniaHolidayProvider.cs, src/Nager.Date/HolidaySystem.cs
=> Add Armenia

src/Nager.Date.UnitTest/Common/OrthodoxProviderTest.cs, src/Nager.Date.UnitTest/Helpers/OrthodoxEasterSundayHelper.cs, src/Nager.Date/ReligiousProviders/OrthodoxProvider.cs
Calculate correctly for previous and future centuries
=> Fix Othodox Easter Sunday calculation

src/Nager.Date.UnitTest/Countries/AustraliaTest.cs, src/Nager.Date/HolidayProviders/AustraliaHolidayProvider.cs
https://github.com/nager/Nager.Date/issues/608
=> Australia - Fix Easter Sunday

src/Nager.Date/HolidayProviders/GermanyHolidayProvider.cs
Remove Hessen
https://github.com/nager/Nager.Date/issues/623
=> Germany - Fix Easter Sunday

src/Nager.Date/HolidayProviders/SwitzerlandHolidayProvider.cs
https://github.com/nager/Nager.Date/issues/634
=> Switzerland - Fix Whit Monday and Corpus Christi

src/Nager.Date/HolidayProviders/CyprusHolidayProvider.cs
Easter Tuesday is only a holiday for banks
=> Cyprus - Fix Easter Tuesday

src/Nager.Date/HolidayProviders/GreeceHolidayProvider.cs
https://github.com/nager/Nager.Date/issues/640
=> Greece - Fix Labour Day for 2024

src/Nager.Date/HolidayProviders/SouthAfricaHolidayProvider.cs
https://github.com/nager/Nager.Date/issues/641
=> South Africa - Add Election Day for 2024

src/Nager.Date/HolidayProviders/SwitzerlandHolidayProvider.cs
https://github.com/nager/Nager.Date/issues/660
=> Switzerland - Fix Rebublic Day (Neuchâtel)

src/Nager.Date/HolidayProviders/BrazilHolidayProvider.cs
https://github.com/nager/Nager.Date/issues/646
=> Brazil - Add Black Awareness Day

src/Nager.Date/HolidayProviders/UkraineHolidayProvider.cs
https://github.com/nager/Nager.Date/issues/663
=> Ukraine - Add Statehood Day

src/Nager.Date/HolidayProviders/SwitzerlandHolidayProvider.cs
https://github.com/nager/Nager.Date/issues/667
=> Switzerland - Add Saints Peter and Paul (Tessin)

src/Nager.Date/HolidayProviders/NewZealandHolidayProvider.cs
https://github.com/nager/Nager.Date/pull/595
https://github.com/nager/Nager.Date/issues/609
=> New Zealand - Fix Auckland Anniversary Day

src/Nager.Date/HolidayProviders/UnitedKingdomHolidayProvider.cs
https://github.com/nager/Nager.Date/issues/644
=> United Kingdom - Fix Early May Bank Holiday 1995

src/Nager.Date/HolidayProviders/AustraliaHolidayProvider.cs
- https://github.com/nager/Nager.Date/issues/565
- https://github.com/nager/Nager.Date/issues/681
=> Australia - Add Friday before AFL Grand Final

src/Nager.Date/HolidayProviders/AustraliaHolidayProvider.cs
- https://github.com/nager/Nager.Date/issues/564
- https://github.com/nager/Nager.Date/issues/682
=> Australia - Add Monarch Birthday for Western Australia

src/Nager.Date/HolidayProviders/SwitzerlandHolidayProvider.cs
=> Switzerland - Fix Epiphany

src/Nager.Date/HolidayProviders/SwitzerlandHolidayProvider.cs
Split into two HolidaySpecifications for HolidayTypes.Public and HolidayTypes.Observance
=> Switzerland - Fix Saint Joseph's Day

src/Nager.Date/HolidayProviders/SwitzerlandHolidayProvider.cs
=> Switzerland - Fix Easter Monday

src/Nager.Date/HolidayProviders/SwitzerlandHolidayProvider.cs
=> Switzerland - Fix Whit Monday

src/Nager.Date/HolidayProviders/SwitzerlandHolidayProvider.cs
=> Switzerland - Fix Corpus Christi

src/Nager.Date/HolidayProviders/SwitzerlandHolidayProvider.cs
=> Switzerland - Fix Immaculate Conception

src/Nager.Date/HolidayProviders/SwitzerlandHolidayProvider.cs
Split into two HolidaySpecifications for HolidayTypes.Public and HolidayTypes.Observance
=> Switzerland - Fix Labour Day

src/Nager.Date.UnitTest/Common/CountryTest.cs, src/Nager.Date/HolidayProviders/SwitzerlandHolidayProvider.cs
=> Switzerland - Fix St. Stephen's Day

src/Nager.Date/HolidayProviders/SwitzerlandHolidayProvider.cs
=> Switzerland - Fix Näfels procession and fix Epiphany

src/Nager.Date/HolidayProviders/ArgentinaHolidayProvider.cs
- https://github.com/nager/Nager.Date/issues/685
=> Argentina - Fix Remove ObservedRuleSet for Carnival

src/Nager.Date/HolidaySystem.cs
Fixed typo Expried to Expired.
=> Fix typo Expired

src/Nager.Date/HolidayProviders/UnitedKingdomHolidayProvider.cs
- https://github.com/nager/Nager.Date/issues/707
Merge entries for the same day
=> United Kingdom - Fix New Year's Day

src/Nager.Date/HolidayProviders/SwitzerlandHolidayProvider.cs
Adjustments according to legal texts
=> Switzerland - Fix holiday list

src/Nager.Date/HolidayProviders/SloveniaHolidayProvider.cs
- https://github.com/nager/Nager.Date/issues/737
=> Slovenia - Fix observance holidays and holiday naming

src/Nager.Date/HolidayProviders/SlovakiaHolidayProvider.cs
- https://github.com/nager/Nager.Date/issues/747
=> Slovakia - Fix Day of the Constitution

src/Nager.Date/HolidayProviders/SlovakiaHolidayProvider.cs
- https://github.com/nager/Nager.Date/issues/757
=> Slovakia - Fix Day of the Constitution before 2024

src/Nager.Date/HolidayProviders/JerseyHolidayProvider.cs
- https://github.com/nager/Nager.Date/issues/771
=> Jersey - Fix Early May Bank Holiday

src/Nager.Date.UnitTest/Countries/AustriaTest.cs, src/Nager.Date/HolidayProviders/AustriaHolidayProvider.cs
=> fix: Austria - Missing public holiday (#749)

src/Nager.Date/HolidayProviders/JapanHolidayProvider.cs
- https://github.com/nager/Nager.Date/issues/764
=> Japan - Fix Holiday shift for Greenery Day

src/Nager.Date/HolidayProviders/AustraliaHolidayProvider.cs
- https://github.com/nager/Nager.Date/issues/781
=> Australia - Fix King's Birthday

src/Nager.Date/HolidayProviders/ArgentinaHolidayProvider.cs
- https://github.com/nager/Nager.Date/issues/784
=> Argentina - Fix Good Friday

src/Nager.Date/HolidayProviders/NetherlandsHolidayProvider.cs
- https://github.com/nager/Nager.Date/issues/786
=> Netherlands - Fix Good Friday

src/Nager.Date/HolidayProviders/FaroeIslandsHolidayProvider.cs
- https://github.com/nager/Nager.Date/issues/801
=> Faroe Islands - Fix duplicate holiday General Prayer Day

src/Nager.Date/HolidayProviders/EgyptHolidayProvider.cs
- https://github.com/nager/Nager.Date/issues/805
=> Egypt - Fix Sinai Liberation Day and June 30 Revolution

src/Nager.Date/HolidayProviders/SingaporeHolidayProvider.cs
- https://github.com/nager/Nager.Date/issues/808
=> Singapore - Confirmed Hari Raya Haji 2025

src/Nager.Date/HolidayProviders/NamibiaHolidayProvider.cs
- https://github.com/nager/Nager.Date/issues/818
=> Nambia - Add Genocide Remembrance Day

src/Nager.Date/HolidayProviders/BelizeHolidayProvider.cs
- https://www.pressoffice.gov.bz/wp-content/uploads/2023/11/Nov-6-PR240-23-PUBLIC-AND-BANK-HOLIDAYS-2024.pdf
- https://www.pressoffice.gov.bz/wp-content/uploads/2024/10/Oct-21-PR163-24-Public-and-Bank-Holidays-2025.pdf
=> Belize - Holiday adjustments
